/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package p1;
import java.sql.*;
import javax.swing.JOptionPane;
import oracle.jdbc.OraclePreparedStatement;
import oracle.jdbc.OracleResultSet;

/**
 *
 * @author Zotac
 */
public class Login extends javax.swing.JFrame {
    Connection conn = JavaConnectDB.ConnectDB();
    OraclePreparedStatement pst = null;
    OracleResultSet rs = null;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        A1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        A2 = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("!!!!!!!!--------University Portal -------!!!!!!!!");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Password:");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Email:");

        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton2.setText("Admin (Full Control)");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton3.setText("Instrutor (Half Control)");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton4.setText("Student (View Only)");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1)
                            .addComponent(A1)
                            .addComponent(A2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(A1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(A2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton1))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
        int z =0;    
        //Searching In Admin Table
        String sql1 = "select * from admin where first_name=? and pass = ?";
        pst = (OraclePreparedStatement) conn.prepareStatement(sql1);
        pst.setString(1,A1.getText().trim());
        pst.setString(2,A2.getText().trim());
        rs = (OracleResultSet) pst.executeQuery();
        if(rs.next()){
            sql1 ="update admin set A=?";
            pst = (OraclePreparedStatement) conn.prepareStatement(sql1);
            pst.setString(1,"0");
            rs = (OracleResultSet) pst.executeQuery();
            sql1 ="update admin set A=? where first_name=? and pass = ?";
            pst = (OraclePreparedStatement) conn.prepareStatement(sql1);
            pst.setString(1,"1");
            pst.setString(2,A1.getText().trim());
            pst.setString(3,A2.getText().trim());
            rs = (OracleResultSet) pst.executeQuery();
            new AMenu().setVisible(true);
            z =1; 
            sql1 ="update std set A=?";
            pst = (OraclePreparedStatement) conn.prepareStatement(sql1);
            pst.setString(1,"0");
            rs = (OracleResultSet) pst.executeQuery();
            sql1 ="update instructor set A=?";
            pst = (OraclePreparedStatement) conn.prepareStatement(sql1);
            pst.setString(1,"0");
            rs = (OracleResultSet) pst.executeQuery();
            this.dispose();
           } 
        
        
        //Searching In Student Table 
        sql1 = "select * from std where first_name=? and pass = ?";
        pst = (OraclePreparedStatement) conn.prepareStatement(sql1);
        pst.setString(1,A1.getText().trim());
        pst.setString(2,A2.getText().trim());
        rs = (OracleResultSet) pst.executeQuery();
            if(rs.next()){
            if(rs.getString(6).equals("0")){
              String p =JOptionPane.showInputDialog(null,"Enter The Password");
              sql1 ="update std set pass=? where first_name=? and pass = ?";
              pst = (OraclePreparedStatement) conn.prepareStatement(sql1);
              pst.setString(1,p);
              pst.setString(2,A1.getText().trim());
              pst.setString(3,A2.getText().trim());
              rs = (OracleResultSet) pst.executeQuery();
              JOptionPane.showMessageDialog(null, "Password Updated Successfully");
            }
            sql1 ="update std set A=?";
            pst = (OraclePreparedStatement) conn.prepareStatement(sql1);
            pst.setString(1,"0");
            rs = (OracleResultSet) pst.executeQuery();
            sql1 ="update std set A=? where first_name=? and pass = ?";
            pst = (OraclePreparedStatement) conn.prepareStatement(sql1);
            pst.setString(1,"1");
            pst.setString(2,A1.getText().trim());
            pst.setString(3,A2.getText().trim());
            rs = (OracleResultSet) pst.executeQuery();  
            new AMenu().setVisible(true);
            z =1; 
            sql1 ="update admin set A=?";
            pst = (OraclePreparedStatement) conn.prepareStatement(sql1);
            pst.setString(1,"0");
            rs = (OracleResultSet) pst.executeQuery();
            sql1 ="update instructor set A=?";
            pst = (OraclePreparedStatement) conn.prepareStatement(sql1);
            pst.setString(1,"0");
            rs = (OracleResultSet) pst.executeQuery();
            this.dispose();
           }
            
        //Searching In Instructor Table   
        sql1 = "select * from instructor where NAME=? and PASS = ?";
        pst = (OraclePreparedStatement) conn.prepareStatement(sql1);
        pst.setString(1,A1.getText().trim());
        pst.setString(2,A2.getText().trim());
        rs = (OracleResultSet) pst.executeQuery();
            if(rs.next()){
              if(rs.getString(6).equals("0")){
              String p =JOptionPane.showInputDialog(null,"Enter The Password");
              sql1 ="update instructor set pass=? where Name=? and pass = ?";
              pst = (OraclePreparedStatement) conn.prepareStatement(sql1);
              pst.setString(1,p);
              pst.setString(2,A1.getText().trim());
              pst.setString(3,A2.getText().trim());
              rs = (OracleResultSet) pst.executeQuery();
              JOptionPane.showMessageDialog(null, "Password Updated Successfully");
            }
            sql1 ="update instructor set A=?";
            pst = (OraclePreparedStatement) conn.prepareStatement(sql1);
            pst.setString(1,"0");
            rs = (OracleResultSet) pst.executeQuery();
            sql1 ="update instructor set A=? where Name=? and pass = ?";
            pst = (OraclePreparedStatement) conn.prepareStatement(sql1);
            pst.setString(1,"1");
            pst.setString(2,A1.getText().trim());
            pst.setString(3,A2.getText().trim());
            rs = (OracleResultSet) pst.executeQuery();
            new AMenu().setVisible(true);
            z =1; 
            sql1 ="update std set A=?";
            pst = (OraclePreparedStatement) conn.prepareStatement(sql1);
            pst.setString(1,"0");
            rs = (OracleResultSet) pst.executeQuery();
            sql1 ="update admin set A=?";
            pst = (OraclePreparedStatement) conn.prepareStatement(sql1);
            pst.setString(1,"0");
            rs = (OracleResultSet) pst.executeQuery();
            this.dispose();
           }
            if(z==0){
                JOptionPane.showMessageDialog(null, "Invaild Login INFO");
                A1.setText("");
                A2.setText("");
            } 
            pst.close();
	    rs.close();
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        A1.setText("Hina");
        A2.setText("123");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        A1.setText("admin1");
        A2.setText("123");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        A1.setText("Yasir");
        A2.setText("123");
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField A1;
    private javax.swing.JPasswordField A2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
